# Generated by Django 3.2.5 on 2021-07-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionary_id',
            new_name='questionary',
        ),
    ]
