# Generated by Django 3.2.5 on 2021-07-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0002_auto_20210716_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Тип вариантов ответов')),
            ],
            options={
                'verbose_name': 'Тип ответов',
                'verbose_name_plural': 'Типы ответов',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questionary.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questionary.questiontype', verbose_name='Тип ответов'),
        ),
    ]
