# Generated by Django 3.2.5 on 2021-07-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0003_auto_20210716_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='start_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата старта'),
        ),
    ]
