# Generated by Django 3.2.5 on 2021-07-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0004_auto_20210717_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='quest_text',
        ),
    ]
