# Generated by Django 3.2.5 on 2021-07-18 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0005_auto_20210717_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionary.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionary.questionary', verbose_name='Опрос'),
        ),
    ]
